# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :test, :development do
  gem 'pry'
  gem 'pry-nav'
  gem 'rubocop', require: false
end

group :test do
  gem 'database_cleaner'
  gem 'factory_girl'
  gem 'rspec'
  gem 'simplecov',         require: false
end
